#!/usr/bin/env python3
"""VoiceVault - macOS Menu Bar App

A privacy-first voice note-taking app:
- Dictate: hold hotkey, speak, text appears at cursor
- Meeting: record, transcribe, summarize, export to Obsidian

Usage:
    python src/app.py

Requires: rumps, pynput, sounddevice, numpy, faster-whisper, pyperclip
"""

import rumps
import threading
import time
from pathlib import Path
import sys

# Add project root to path so 'src' package imports work
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.config import CONFIG
from src.audio.streamer import AudioStreamer
from src.transcription.engine import ENGINE
from src.injection.macos import inject_text
from src.meeting.session import MeetingManager
from src.onboarding import needs_onboarding, run_onboarding
from src.ui.floating_panel import DictationFloatPanel
from src.transcript_log import TranscriptLog


# Maximum gap between a key release and the next press to count as a
# double-tap (and enter hands-free mode).
HOTKEY_DOUBLE_TAP_WINDOW_SEC = 0.35


class VoiceVaultApp(rumps.App):
    def __init__(self):
        super().__init__("VoiceVault", icon=self._resolve_icon_path(),
                         quit_button="Quit")

        # Title is a single-glyph so the SF Symbol icon makes the slot
        # visually identifiable at a glance; state changes flip both.
        self.title = "🎙"

        self._dictation_streamer: AudioStreamer = None
        self._dictation_audio_buffer: list = []
        self._meeting_manager = MeetingManager()
        self._dictation_panel = DictationFloatPanel()
        self._transcript_log = TranscriptLog(CONFIG.data_dir)

        # Last fully-flushed dictation (post-stop). Used by the Replay menu
        # item so the user can re-paste into a different field.
        self._last_injection: str = ""

        # Hotkey mode: False = push-to-talk (hold to dictate, release to stop)
        #              True  = hands-free (double-tap activates; single press
        #                      deactivates; key-release no-ops during dictation)
        self._hands_free: bool = False
        self._last_release_monotonic: float = 0.0  # for double-tap window

        # Menu items
        self._build_menu()

        # Start hotkey listener in background thread
        self._hotkey_thread = threading.Thread(target=self._listen_hotkeys, daemon=True)
        self._hotkey_thread.start()

        # Notes API (search + RAG chat) for the Electron dashboard, plus an
        # initial background index of anything not yet indexed.
        self._api_thread = threading.Thread(target=self._run_api_server, daemon=True)
        self._api_thread.start()
        self._index_thread = threading.Thread(target=self._reindex_notes, daemon=True)
        self._index_thread.start()

    @staticmethod
    def _run_api_server():
        """Run the local notes API (src/api/server.py) for the Electron
        dashboard. Failures here (e.g. pysqlite3 missing) shouldn't take
        down dictation/meeting mode, so they're caught and logged."""
        try:
            from src.api.server import run as run_api
            run_api()
        except Exception as e:
            print(f"[API] Notes API server failed to start: {e}")

    @staticmethod
    def _reindex_notes():
        try:
            from src.search.indexer import index_all
            result = index_all()
            print(f"[Search] Indexed {result['indexed']}, "
                  f"skipped {result['skipped']} unchanged, "
                  f"{result['total_chunks']} chunks total")
        except Exception as e:
            print(f"[Search] Indexing failed: {e}")

    @staticmethod
    def _resolve_icon_path() -> str:
        """Return the path to the SF Symbol menu-bar icon if it exists.

        Generated by `scripts/build-icon.py`. If the icon files are missing
        (e.g. fresh clone), falls back to rumps' default title-only behavior.
        """
        repo_root = Path(__file__).resolve().parent.parent
        icon = repo_root / "data" / "voicevault_icon.png"
        return str(icon) if icon.exists() else None

    def _build_menu(self):
        """Build the menu bar menu."""
        self.menu = [
            rumps.MenuItem("Dictate", callback=self._toggle_dictation),
            rumps.MenuItem("Meeting", callback=self._toggle_meeting),
            rumps.MenuItem("Open Dashboard", callback=self._open_dashboard),
            None,  # separator
            rumps.MenuItem("Replay Last Dictation", callback=self._replay_last),
            rumps.MenuItem("Open Today\u2019s Log", callback=self._open_todays_log),
            None,
            rumps.MenuItem("Settings", callback=self._open_settings),
            rumps.MenuItem("Obsidian Vault", callback=self._open_vault),
            None,
            rumps.MenuItem("About", callback=self._show_about),
        ]

        # Update menu state
        self._update_menu()
    
    def _update_menu(self):
        """Update menu item labels and the menubar title based on state."""
        dictation_item = self.menu["Dictate"]
        meeting_item = self.menu["Meeting"]

        is_dictating = bool(
            self._dictation_streamer and self._dictation_streamer.is_streaming
        )
        is_recording = self._meeting_manager.is_recording
        # Snapshot for stable menu rendering within one update.
        hands_free = bool(self._hands_free)

        # Dropdown menu labels — reflect push-to-talk vs hands-free.
        if is_dictating:
            if hands_free:
                dictation_item.title = "🟢 Stop Hands-free Dictation"
            else:
                dictation_item.title = "🟢 Stop Dictating (push-to-talk)"
        else:
            dictation_item.title = (
                f"🎙 Dictate (Hold {CONFIG.dictate_hotkey.upper()} for push-to-talk, "
                f"double-tap for hands-free)"
            )

        if is_recording:
            duration = int(self._meeting_manager._recorder.duration)
            mins, secs = divmod(duration, 60)
            meeting_item.title = f"🔴 Stop Meeting ({mins}:{secs:02d})"
        else:
            meeting_item.title = "📹 Record Meeting"

        # Replay & log openers carry the most-recent dictation length
        # (or "(empty)" when nothing has been captured yet).
        replay = self.menu["Replay Last Dictation"]
        replay_title_prefix = "\u21bb Replay Last"
        if self._last_injection:
            replay.title = f"{replay_title_prefix} ({len(self._last_injection)} chars)"
        else:
            replay.title = f"{replay_title_prefix} (none yet)"

        log = self.menu["Open Today\u2019s Log"]
        log.title = "\U0001F4D6 Open Today\u2019s Log"

        # Menubar title: SF Symbol icon carries the visual identity; the
        # title string is just the status indicator. Priority: recording
        # > dictating > idle.
        if is_recording:
            duration = int(self._meeting_manager._recorder.duration)
            mins, secs = divmod(duration, 60)
            self.title = f"🔴{mins}:{secs:02d}"
        elif is_dictating:
            self.title = "HF" if hands_free else "●"
        else:
            self.title = ""
    
    def _toggle_dictation(self, _):
        """Toggle dictation via menubar click.

        Click-to-start acts as hands-free (a click has no "hold" affordance).
        """
        is_streaming = bool(self._dictation_streamer and self._dictation_streamer.is_streaming)
        if self._hands_free or is_streaming:
            self._stop_dictation()
            return
        self._hands_free = True
        self._start_dictation()
    
    def _start_dictation(self):
        """Start buffering audio. No transcription happens until release —
        Wispr-Flow-style push-to-talk: hold, speak, release, then the whole
        utterance is transcribed once and injected in one shot. Avoids the
        repeated-re-decode-of-a-growing-buffer approach, which made Whisper
        prone to repetition-loop hallucinations on longer dictations.
        """
        if self._dictation_streamer and self._dictation_streamer.is_streaming:
            return  # idempotent

        self._dictation_audio_buffer = []
        self._dictation_injected_text = ""

        def on_audio_chunk(audio_chunk):
            self._dictation_audio_buffer.append(audio_chunk)

        self._dictation_streamer = AudioStreamer(callback=on_audio_chunk)
        self._dictation_streamer.start()

        # Show floating pill (Wispr Flow style: bottom, animated waveform).
        # Default mode label is "Push-to-Talk"; double-tap upgrade flips
        # it to "Hands-free" before the user starts speaking. Text stays
        # blank until release — only the waveform animates while listening.
        self._dictation_panel.show("", mode="Push-to-Talk" if not self._hands_free else "Hands-free")

        self._update_menu()
        try:
            rumps.notification("VoiceVault", "Dictation Started", "Speak now...")
        except Exception:
            pass

    def _stop_dictation(self):
        """Stop capture and transcribe the whole recording in a single pass.

        One decode of the complete utterance, injected all at once — no
        incremental re-decoding of a growing buffer.
        """
        import numpy as np
        if self._dictation_streamer:
            self._dictation_streamer.stop()
            self._dictation_streamer = None

        # Any path that stops dictation also leaves hands-free mode.
        self._hands_free = False

        # Hide the floating pill
        if hasattr(self, "_dictation_panel"):
            self._dictation_panel.dismiss()

        self._update_menu()

        full_text = ""
        if self._dictation_audio_buffer:
            full_audio = np.concatenate(self._dictation_audio_buffer)
            # Static glossary only — no rolling context from the previous
            # dictation is mixed in. See docs/DICTATION_CONTEXT_PROMPT.md
            # for why that was deferred rather than implemented.
            full_text = ENGINE.transcribe_stream(full_audio, initial_prompt=CONFIG.initial_prompt) or ""
            full_text = full_text.strip()
            if full_text:
                inject_text(full_text)

        self._dictation_injected_text = full_text

        # Persist + cache finished dictation. Replay menu and daily log
        # both depend on `_last_injection` being the *final* output.
        if full_text:
            self._last_injection = full_text
            if hasattr(self, "_transcript_log"):
                try:
                    self._transcript_log.append(full_text, label="Dictation")
                except Exception as e:
                    print(f"[Log] failed to append: {e}")
        self._update_menu()

        try:
            rumps.notification(
                "VoiceVault", "Dictation Stopped",
                f"Captured: {len(full_text)} chars"
            )
        except Exception:
            pass
    
    def _toggle_meeting(self, _):
        """Toggle meeting recording."""
        if self._meeting_manager.is_recording:
            self._stop_meeting()
        else:
            self._start_meeting()
    
    def _start_meeting(self):
        """Start a new meeting recording."""
        window = rumps.Window(
            title="New Meeting",
            message="Enter meeting title:",
            default_text="Meeting",
            ok="Start",
            cancel="Cancel"
        )
        response = window.run()
        
        if response.clicked:
            title = response.text or "Untitled Meeting"
            self._meeting_manager.start(title)
            self._update_menu()
            
            # Start timer to update menu
            self._meeting_timer = rumps.Timer(self._update_menu, 1)
            self._meeting_timer.start()
            
            try:
                rumps.notification("VoiceVault", "Meeting Started", title)
            except Exception:
                pass
    
    def _stop_meeting(self):
        """Stop meeting recording and process."""
        if hasattr(self, '_meeting_timer'):
            self._meeting_timer.stop()
        
        session = self._meeting_manager.stop()
        self._update_menu()
        
        try:
            rumps.notification(
                "VoiceVault", 
                "Meeting Complete", 
                f"{session.title}: {int(session.duration/60)}min"
            )
        except Exception:
            pass
    
    def _add_meeting_note(self, text: str, tag: str = None):
        """Add a note to the current meeting."""
        if self._meeting_manager.is_recording:
            self._meeting_manager.add_note(text, tag)
    
    def _listen_hotkeys(self):
        """Listen for global hotkeys in background thread.

        State machine (driven by `_on_hotkey_press` / `_on_hotkey_release`):

            IDLE            --press, no recent release--> PUSH_TO_TALK      (start)
            IDLE            --press, recent release---->  HANDS_FREE         (start, _hands_free=True)
            PUSH_TO_TALK    --press-------------------->  (ignore, key held)
            PUSH_TO_TALK    --release----------------->  IDLE               (stop)
            HANDS_FREE      --press-------------------->  IDLE               (stop, _hands_free=False)
            HANDS_FREE      --release----------------->  (ignore)

        Double-tap window: HOTKEY_DOUBLE_TAP_WINDOW_SEC s between a release
        and the next press.
        """
        hk = CONFIG.dictate_hotkey.lower().strip()
        if hk == 'fn':
            self._listen_fn_hotkey()
        else:
            self._listen_pynput_hotkey(hk)

    def _listen_fn_hotkey(self):
        """Listen for the physical Fn/Globe key via a raw flagsChanged tap.

        The Fn key (macOS virtual keycode 63 / kVK_Function) does not behave
        like a normal key as far as pynput's press/release synthesis is
        concerned: even with System Settings -> Keyboard -> "Press Fn key
        to: Do Nothing" set (required — otherwise macOS eats the press
        entirely for Emoji & Symbols / Dictation before any third-party
        listener sees it), pynput's Listener only ever observed a release
        event for it in testing, never a press. A raw CGEventTap watching
        kCGEventFlagsChanged and checking kCGEventFlagMaskSecondaryFn
        reliably sees both transitions, so we bypass pynput for this one
        key rather than trust its abstraction here.
        """
        try:
            import Quartz
        except ImportError:
            print("pyobjc (Quartz) not installed — required for the Fn hotkey. "
                  "Install with: pip install pyobjc-framework-Quartz")
            return

        FN_KEYCODE = 0x3F  # kVK_Function

        def callback(proxy, event_type, event, refcon):
            if event_type == Quartz.kCGEventFlagsChanged:
                keycode = Quartz.CGEventGetIntegerValueField(event, Quartz.kCGKeyboardEventKeycode)
                if keycode == FN_KEYCODE:
                    fn_down = bool(Quartz.CGEventGetFlags(event) & Quartz.kCGEventFlagMaskSecondaryFn)
                    if fn_down:
                        self._on_hotkey_press()
                    else:
                        self._on_hotkey_release()
            return event

        tap = Quartz.CGEventTapCreate(
            Quartz.kCGSessionEventTap,
            Quartz.kCGHeadInsertEventTap,
            Quartz.kCGEventTapOptionListenOnly,
            Quartz.CGEventMaskBit(Quartz.kCGEventFlagsChanged),
            callback,
            None,
        )
        if tap is None:
            print("[Hotkeys] Failed to create Fn key event tap — check Input "
                  "Monitoring permission in System Settings > Privacy & Security.")
            return

        run_loop_source = Quartz.CFMachPortCreateRunLoopSource(None, tap, 0)
        Quartz.CFRunLoopAddSource(Quartz.CFRunLoopGetCurrent(), run_loop_source, Quartz.kCFRunLoopCommonModes)
        Quartz.CGEventTapEnable(tap, True)
        print(f"[Hotkeys] Listening for: fn "
              f"(double-tap within {HOTKEY_DOUBLE_TAP_WINDOW_SEC}s → hands-free)")
        Quartz.CFRunLoopRun()

    def _listen_pynput_hotkey(self, hk: str):
        """Listen for any non-Fn hotkey via pynput (ctrl/cmd/alt/f13-f20/letters)."""
        try:
            from pynput import keyboard

            def _resolve_key(hotkey_str: str):
                """Map a key string to a pynput Key for comparison."""
                key_map = {
                    'ctrl': (keyboard.Key.ctrl, keyboard.Key.ctrl_l, keyboard.Key.ctrl_r),
                    'control': (keyboard.Key.ctrl, keyboard.Key.ctrl_l, keyboard.Key.ctrl_r),
                    'cmd': (keyboard.Key.cmd, keyboard.Key.cmd_l, keyboard.Key.cmd_r),
                    'command': (keyboard.Key.cmd, keyboard.Key.cmd_l, keyboard.Key.cmd_r),
                    'alt': (keyboard.Key.alt, keyboard.Key.alt_l, keyboard.Key.alt_r),
                    'option': (keyboard.Key.alt, keyboard.Key.alt_l, keyboard.Key.alt_r),
                    'shift': (keyboard.Key.shift, keyboard.Key.shift_l, keyboard.Key.shift_r),
                    'f13': (keyboard.Key.f13,),
                    'f14': (keyboard.Key.f14,),
                    'f15': (keyboard.Key.f15,),
                    'f16': (keyboard.Key.f16,),
                    'f17': (keyboard.Key.f17,),
                    'f18': (keyboard.Key.f18,),
                    'f19': (keyboard.Key.f19,),
                    'f20': (keyboard.Key.f20,),
                }
                if hotkey_str in key_map:
                    return key_map[hotkey_str]
                if hotkey_str.startswith('f') and hotkey_str[1:].isdigit():
                    fn = int(hotkey_str[1:])
                    if 1 <= fn <= 20:
                        return (getattr(keyboard.Key, f'f{fn}'),)
                return ('char', hotkey_str)

            target = _resolve_key(hk)

            def _matches(key, target):
                if target[0] == 'char':
                    return hasattr(key, 'char') and key.char == target[1]
                return key in target

            def on_press(key):
                if _matches(key, target):
                    self._on_hotkey_press()

            def on_release(key):
                if _matches(key, target):
                    self._on_hotkey_release()
                return True

            print(f"[Hotkeys] Listening for: {hk} "
                  f"(double-tap within {HOTKEY_DOUBLE_TAP_WINDOW_SEC}s → hands-free)")
            with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
                listener.join()
        except ImportError:
            print("pynput not installed. Install with: pip install pynput")
        except Exception as e:
            print(f"Hotkey listener error: {e}")

    def _on_hotkey_press(self) -> None:
        """Apply the press-event transition of the hotkey state machine.

        Runs on the pynput listener thread. Boolean reads/writes are
        GIL-atomic so no lock is needed for the single-flag state.
        """
        if self._hands_free:
            # Press during hands-free: stops dictation and exits hands-free.
            self._stop_dictation()
            return
        is_streaming = bool(
            self._dictation_streamer and self._dictation_streamer.is_streaming
        )
        if is_streaming:
            # Extra presses while the user holds the hotkey in push-to-talk
            # mode are a no-op (avoids restarting accidentally).
            return
        # IDLE: first press — but check for double-tap from a recent release.
        if self._last_release_monotonic > 0.0:
            gap = time.monotonic() - self._last_release_monotonic
            self._last_release_monotonic = 0.0
            if gap < HOTKEY_DOUBLE_TAP_WINDOW_SEC:
                self._hands_free = True
                # Pre-set the pill caption so it shows "Hands-free" the
                # instant the dictation starts on this second press.
                if hasattr(self, "_dictation_panel"):
                    self._dictation_panel.update_mode("Hands-free")
        self._start_dictation()

    def _on_hotkey_release(self) -> None:
        """Apply the release-event transition of the hotkey state machine."""
        self._last_release_monotonic = time.monotonic()
        if self._hands_free:
            return  # don't stop on release in hands-free mode
        if self._dictation_streamer and self._dictation_streamer.is_streaming:
            self._stop_dictation()

    def _replay_last(self, _):
        """Re-paste the most recent finished dictation at the cursor."""
        if not self._last_injection:
            print("[Replay] no prior dictation to replay")
            return
        # Append a trailing space so subsequent typing isn't jammed
        # against the injected block.
        inject_text(self._last_injection + " ")
        print(f"[Replay] re-pasted {len(self._last_injection)} chars "
              f"from the last completed dictation")

    def _open_todays_log(self, _):
        """Open today's transcript log in the user's default Markdown
        viewer (typically Obsidian if a vault is configured, otherwise
        TextEdit / Preview via Launch Services)."""
        import subprocess
        path = self._transcript_log.todays_file()
        if not path.exists():
            try:
                rumps.notification("VoiceVault", "Log", "No dictations yet today.")
            except Exception:
                pass
            return
        subprocess.run(["open", str(path)])

    def _open_settings(self, _):
        """Open settings dialog."""
        rumps.alert(
            title="Settings",
            message=f"""VoiceVault Settings:

Whisper Model: {CONFIG.whisper_model}
STT Backend: {CONFIG.whisper_backend}
Ollama URL: {CONFIG.ollama_url}
Ollama Model: {CONFIG.ollama_model}
Obsidian Vault: {CONFIG.obsidian_vault}

Edit .env file to change settings.
"""
        )
    
    def _open_dashboard(self, _):
        """Launch the Electron notes dashboard (browse, search, ask)."""
        import subprocess
        repo_root = Path(__file__).resolve().parent.parent
        electron_dir = repo_root / "electron"
        node_modules = electron_dir / "node_modules"
        if not node_modules.exists():
            try:
                rumps.alert(
                    title="Dashboard Setup Needed",
                    message=f"First-time setup: run this once, then try again:\n\n"
                            f"cd {electron_dir}\nnpm install",
                )
            except Exception:
                pass
            print(f"[Dashboard] electron/node_modules missing — run `npm install` in {electron_dir}")
            return
        subprocess.Popen(
            ["npm", "start"],
            cwd=str(electron_dir),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

    def _open_vault(self, _):
        """Open Obsidian vault folder."""
        import subprocess
        if CONFIG.obsidian_vault and CONFIG.obsidian_vault.exists():
            subprocess.run(["open", str(CONFIG.obsidian_vault)])
        else:
            rumps.alert("Vault Not Found", "Obsidian vault path not configured.")
    
    def _show_about(self, _):
        """Show about dialog."""
        rumps.alert(
            title="VoiceVault",
            message="Privacy-first voice note-taking.\n\n"
                    f"Dictate: Hold {CONFIG.dictate_hotkey.upper()} to speak anywhere\n"
                    "Meeting: Record and summarize meetings\n\n"
                    "Open Source • Local-First • Obsidian Ready"
        )


if __name__ == "__main__":
    if needs_onboarding():
        run_onboarding()
        # Reload config so the new vault path and user preferences are picked up
        from src.config import Config
        import src.config as _config_module
        _config_module.CONFIG = Config.from_env()
    app = VoiceVaultApp()
    app.run()
